version: "3.9"
services:
  postgres:
    image: postgres:13.12
    environment:
      
      POSTGRES_DB: "postgre"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"