-- DROP ROLE pols1;

CREATE ROLE pols1 WITH 
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	LOGIN
	NOREPLICATION
	NOBYPASSRLS
	CONNECTION LIMIT -1;

-- Permissions

GRANT USAGE ON SCHEMA case_test TO pols1;
GRANT DELETE, UPDATE, INSERT, TRUNCATE, TRIGGER, REFERENCES, SELECT ON TABLE case_test.departments TO pols1;
GRANT DELETE, UPDATE, INSERT, TRUNCATE, TRIGGER, REFERENCES, SELECT ON TABLE case_test.employees TO pols1;
GRANT DELETE, UPDATE, INSERT, TRUNCATE, TRIGGER, REFERENCES, SELECT ON TABLE case_test.employees_hours TO pols1;
GRANT DELETE, UPDATE, INSERT, TRUNCATE, TRIGGER, REFERENCES, SELECT ON TABLE case_test.positions TO pols1;
GRANT DELETE, UPDATE, INSERT, TRUNCATE, TRIGGER, REFERENCES, SELECT ON TABLE case_test.working_phones TO pols1;









-- DROP ROLE pols2;

CREATE ROLE pols2 WITH 
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	LOGIN
	NOREPLICATION
	NOBYPASSRLS
	CONNECTION LIMIT -1;

-- Permissions

GRANT USAGE ON SCHEMA case_test TO pols2;
GRANT SELECT ON TABLE case_test.departments TO pols2;
GRANT SELECT ON TABLE case_test.employees TO pols2;
GRANT SELECT ON TABLE case_test.employees_hours TO pols2;
GRANT SELECT ON TABLE case_test.positions TO pols2;
GRANT SELECT ON TABLE case_test.working_phones TO pols2;
GRANT USAGE ON SCHEMA case_three TO pols2;
GRANT DELETE, INSERT ON TABLE case_three.departments TO pols2 WITH GRANT OPTION;
GRANT DELETE, INSERT ON TABLE case_three.employees TO pols2 WITH GRANT OPTION;
GRANT DELETE, INSERT ON TABLE case_three.employees_hours TO pols2 WITH GRANT OPTION;
GRANT DELETE, INSERT ON TABLE case_three.positions TO pols2 WITH GRANT OPTION;
GRANT DELETE, INSERT ON TABLE case_three.working_phones TO pols2 WITH GRANT OPTION;


GRANT opg TO pols2;